### ISSUE TITLE
[Feat] - Implementing Issue-Template and PR -Template

### ISSUE THREAD

**Issue by Sibam-Paul** [UTSAVS26/PySnippets#1]
Will add a nice issue template for BUG, DOCS , Feature 
Will also add a PR-template 

@UTSAVS26 **Please assign me this issue under _hacktoberfest_ so that I can work on it**

**Comment by UTSAVS26** [comment]
> Will add a nice issue template for BUG, DOCS , Feature 
> Will also add a PR-template 
> 
> @UTSAVS26 **Please assign me this issue under _hacktoberfest_ so that I can work on it** 

@Sibam-Paul you can start working on it

**Comment by UTSAVS26** [comment]
> @UTSAVS26 Ok proceeding

Look for the already listed templates and update them accordingly and change the folder name too to `.github` for easy navigation and whenever opens a new issue and raise an PR they automatically comes
