### ISSUE TITLE
[Feature Request]: Add Number Conversion Functions in number Folder

### ISSUE THREAD

**Issue by ahmedfarazsyk** [UTSAVS26/PySnippets#10]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description: 
There are currently no issues with the existing functionality of pysnippets. However, I would like to propose the addition of new features to the number folder. Specifically, I plan to add number conversion functions, which include:

1. Decimal to Binary Number Conversion
2. Binary to Decimal Number Conversion

These functions will be useful for users needing basic number system conversions.

### Planned Changes:

- Add a function to convert decimal numbers to binary.
- Add a function to convert binary numbers to decimal.
- Include proper comments for code clarity and maintainability.
- Create unit tests to verify the correctness of the new functions.

### Benefits:
 This feature will extend the functionality of pysnippets, making it more useful for developers needing quick access to number system conversions.

**I am a gssoc-ext, hactoberfeast contributor**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sai-ganesh-0004** [comment]
Hello I would like to work on this Can you assign it to me

**Comment by Mahak-Agrawal-304** [comment]
Can I help too in improvising this conversion, @UTSAVS26 ? Rather than converting from decimal to binary, we can add codes for converting decimal to any base, and from any base to decimal
