### ISSUE TITLE
Addition of Bit Manipulation and Linked List Concepts

### ISSUE THREAD

**Issue by Shariq2003** [UTSAVS26/PySnippets#107]
I want to add Bit Manipulation and Linked List Concept in depth and with full explanation  along with the implementation, because these are important topics of DSA and competitive programming.

**Comment by UTSAVS26** [comment]
@Shariq2003 raise 1 issue at a time based on the rules on discussion.

**Comment by Shariq2003** [comment]
> @Shariq2003 raise 1 issue at a time based on the rules on discussion.

Okay sir, I apologize for this
