### ISSUE TITLE
[Feature Request]: Expanding stats collection by adding- Interquartile Range (IQR) and Covariance

### ISSUE THREAD

**Issue by LitZeus** [UTSAVS26/PySnippets#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To expand the collection of Python code snippets in the /stats/ directory, i would like to add the functions like IQR and Covariance which will enrich the `stats` code snippets quality.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Tejas Athalye

### Participant Role

`gssoc-ext` contributor
`hacktoberfest` contributor

**Comment by SpreadSheets600** [comment]
@UTSAVS26 issue #97
