### ISSUE TITLE
[Feature Request]: ADDITION OF ALL SORTING ALGORITHMS 

### ISSUE THREAD

**Issue by sindhuja184** [UTSAVS26/PySnippets#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to sorting algorithms like bubble sort, mergesort, heapsort, quick sort, selection sort, insertion sort.

This would enhance pysnippets.

Please assign this to me.

Thanks @UTSAVS26 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Sindhuja Didugu

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@sindhuja184 have you checked the repo that these algorithms is not their in the repo?

**Comment by sindhuja184** [comment]
@UTSAVS26, I have checked the repo they are missing.

Hope you assign the task to me.
