### ISSUE TITLE
[Feature Request]: Addition of greedy algorithms

### ISSUE THREAD

**Issue by sindhuja184** [UTSAVS26/PySnippets#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add algorithms like Huffman Coding, Kruskal's algorithm, Prim's algorithm, Fractional Knapsack.

Please assign the issue to me.

Thanks @UTSAVS26 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Sindhuja D 

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@sindhuja184 you can raise 1 issue at a time. You can read other guidelines in discussion page.
