### ISSUE TITLE
[Feature Request]: Changing codes and Adding a Logo(QR Code)

### ISSUE THREAD

**Issue by sindhuja184** [UTSAVS26/PySnippets#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I can enable the user so that he can customize the apperance of the QR codes by changing colors and embedding a logo at center.

Please assign this to me.

Thanks @UTSAVS26 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Sindhuja Didugu

### Participant Role

GSSOC contributor

**Comment by UTSAVS26** [comment]
@sindhuja184 you can raise 1 issue at a time. You can read other guidelines in discussion page.

**Comment by M03anaswi** [comment]
Could you assign me this issue

**Comment by UTSAVS26** [comment]
> Could you assign me this issue @UTSAVS26 
> 

No you need to raise another issue as this issue going to be closed.
