### ISSUE TITLE
[Feature Request]: Add Utility Snippets

### ISSUE THREAD

**Issue by AashishNandakumar** [UTSAVS26/PySnippets#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There are currently no issues with the existing functionality of pysnippets. However, I would like to propose the addition of new utility snippets to enhance the functionality of PySnippets. Specifically, I plan to add the following snippets:

1. Memoization (Caching Function Results)
2. Timer Context Manager
3. Sending an Email (using smtplib)
4. Sorting a List of Dictionaries by Key

These functions will provide developers with efficient solutions for common programming tasks.

Planned Changes:

- Add a function for memoization to cache expensive function call results.
- Create a timer context manager for measuring code execution time.
- Implement a simple email sending function using smtplib.
- Add a function to sort a list of dictionaries by a specified key.
- Include proper comments and docstrings for code clarity and maintainability.
- Create unit tests to verify the correctness of the new functions.

Benefits:
These new snippets will extend the functionality of PySnippets, making it more useful for developers by:

- Improving performance with memoization techniques
- Facilitating easy performance monitoring
- Simplifying email automation tasks
- Enhancing data manipulation capabilities

**I am a gssoc-ext, hactoberfeast contributor**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by UTSAVS26** [comment]
@AashishNandakumar you have closed the issue? Don't you want to work on it?

**Comment by AashishNandakumar** [comment]
Is it acceptable if I turn in this assignment two days later? I understand that these are basic tasks, but I'm running a bit behind schedule.

**Comment by UTSAVS26** [comment]
Yeah sure then raise another issue I am closing this one. All the best.
