### ISSUE TITLE
[Feature Request]: Machine Learning models code-snippets

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PySnippets#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

I would like to add different machine learning models code that are widely used in the data science **classification** and **prediction** purposes. Furthermore share a brief working algorithms using raw python code.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

[Yash K. Saini](https://github.com/yashksaini-coder)

### Participant Role

Gssoc-ext contributor

**Comment by yashksaini-coder** [comment]
@UTSAVS26 can you add labels to this issue & assign it to me. Also tell me what can I precisely do in order for this to be ranked **level 3**

**Comment by yashksaini-coder** [comment]
Hi @UTSAVS26 can you assign me this issue

**Comment by UTSAVS26** [comment]
@yashksaini-coder are you planning to add snippets for ML? 
And for level3 and level2 then you need to fix big or add new feature in the existing code.

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder are you planning to add snippets for ML? And for level3 and level2 then you need to fix big or add new feature in the existing code.

Yes for advance ML techniques, XGB, Catboost, LGBM Ensemble techniques, K-fold,

**Comment by yashksaini-coder** [comment]
They are very advance are effective so could be a very big feature addition to the snippets.

**Comment by yashksaini-coder** [comment]
@UTSAVS26 so can this issue be assigned to me now.

**Comment by yashksaini-coder** [comment]
@UTSAVS26 tell me what code changes will make this `Level 3` issue ?

**Comment by UTSAVS26** [comment]
> @UTSAVS26 tell me what code changes will make this `Level 3` issue ?

If you add new feature in the existing codebase or fix any bug.
