### ISSUE TITLE
[Documentation Update]: fix import statement in README.md

### ISSUE THREAD

**Issue by Panda8Bamboo** [UTSAVS26/PySnippets#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Current import statement is not correct: from pysnippets.strings import reverse_string
Comes up with error when run.

### Suggested Change

Should be: from pysnippets.Strings.string_manipulation import reverse_string
Follows current file structure and runs.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Amber

### Participant Role

GSSOC I think

**Comment by UTSAVS26** [comment]
The error is because that the package is not deployed yet so wait for sometime until it is deployed.
