### ISSUE TITLE
[Documentation Update]: Modification of README.md file.

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [UTSAVS26/PySnippets#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 1) Add animated line separators and GSSoC 2024 Extended Acceptance banner.

This will make the **README.md** file look more attractive and engaging for the Users and Contributors
![image](https://github.com/user-attachments/assets/4dd78a96-9066-4614-bba6-58dd654c3bf7)

### 2) Modifiy the **Contributors section**.
I noticed that the Contributor mention section is not updated:
![image](https://github.com/user-attachments/assets/1d23e74b-7ce5-4ab3-a776-b118533ecc8e)

I want to update the Contributors section in the README.md file and also try to automate the process:
![image](https://github.com/user-attachments/assets/28462a44-9d84-4740-a573-d5cbd10b4878)

### 3) Add a **Team section**
This will help the Contributors know about the Project Admin and who to contact if they face any issues. 
![image](https://github.com/user-attachments/assets/fae867de-c89c-441c-82ba-4b0d6374ef39)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Rajdeep Chakraborty

### Participant Role

**Contributor** 
Program - GSSoC 2024 Extended & Hactoberfest 2024.

**Comment by rajdeepchakraborty-rc** [comment]
@UTSAVS26 Thanks for assigning me the issue. Also I would like to ask whether the issue shouldn't be assigned **level2**? Since I am adding a lot of features.

**Comment by rajdeepchakraborty-rc** [comment]
@UTSAVS26 I noticed that you have another contact section under the **Contributing.md** file. Do you want me to add the above Team section there too? 
![image](https://github.com/user-attachments/assets/08b6e797-f9b6-4273-a394-0f9546e3df1b)

**Comment by rajdeepchakraborty-rc** [comment]
Also I am thinking of adding a redirect to the **Contributing.md** file from the **README.md** file
![image](https://github.com/user-attachments/assets/7526c097-42c2-493e-9283-d180b82e2474)
Please let me know if that would be fine.

**Comment by UTSAVS26** [comment]
> @UTSAVS26 Thanks for assigning me the issue. Also I would like to ask whether the issue shouldn't be assigned **level2**? Since I am adding a lot of features.

They are only related to documentation so they come under level1 only.

**Comment by rajdeepchakraborty-rc** [comment]
> > @UTSAVS26 Thanks for assigning me the issue. Also I would like to ask whether the issue shouldn't be assigned **level2**? Since I am adding a lot of features.
> 
> They are only related to documentation so they come under level1 only.

Thanks for the reply.

**Comment by rajdeepchakraborty-rc** [comment]
@UTSAVS26 Please reply to the other matters

**Comment by rajdeepchakraborty-rc** [comment]
Since your project is accepted under both the GSSoC 2024 Extended and Hacktoberfest 2024 programs, I have added both the banners:
![image](https://github.com/user-attachments/assets/6a2a2ea0-c935-4640-b8da-d8fc035688d0)

**Comment by UTSAVS26** [comment]
> @UTSAVS26 Please reply

You can add the things you want, i will check them directly in PR.

**Comment by rajdeepchakraborty-rc** [comment]
> > @UTSAVS26 Please reply
> 
> You can add the things you want, i will check them directly in PR.

Ok thanks for the reply.
