### ISSUE TITLE
[Feature Request]: Adding a fibonacci sequence generator

### ISSUE THREAD

**Issue by Kritika75** [UTSAVS26/PySnippets#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We can generate Fibonacci numbers up to a specified count or maximum value 

Adding a Fibonacci Sequence Generator to PySnippets makes the library more useful by providing a handy tool for a well-known math concept. The generator works efficiently, avoiding slowdowns often caused by recursive methods, which is great for quick calculations. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Kritika Singh

### Participant Role

Contributor at GSSoC'24 ext

@UTSAVS26 can you assign me this?

**Comment by sociallyencrypted** [comment]
Full Name
Mehul Arora

Participant Role
Contributor at GSSoC'24 ext, Hacktoberfest

Would love to be assigned to this issue!

**Comment by Kritika75** [comment]
Hey @UTSAVS26 this issue is opened by me so please assign it to me only

**Comment by UTSAVS26** [comment]
> Full Name
> Mehul Arora
> 
> Participant Role
> Contributor at GSSoC'24 ext, Hacktoberfest
> 
> Would love to be assigned to this issue!
> 

You can raise another issue.
