### ISSUE TITLE
Adding greedy algorithms

### ISSUE THREAD

**Issue by Aditijainnn** [UTSAVS26/PySnippets#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add greedy algorithms: 
Greedy algorithms are important because they provide efficient solutions to optimization problems by making locally optimal choices at each step. They are easy to implement and often yield globally optimal solutions for specific problem types.
Here are types of  greedy algorithms:
Activity Selection Problem
Expedi problem
Fractional Knapsack Problem
Indian denomination problem
Maximum and minimum difference problem
Optimal merge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Aditi jain

### Participant Role

Contributor

**Comment by UTSAVS26** [comment]
@Aditijainnn are you planning to add greedy algorithms as a snippets or just code?
