### ISSUE TITLE
[Documentation Update]: Enhance README

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PySnippets#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Your PySnippets documentation can be improved

### Suggested Change

- Add image badges
- Personal Discord join link
- stargazers & forkers roster
- Contributors list showcase

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Yash K. Saini

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@yashksaini-coder work on 1 issue at time I am closing this one.

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder work on 1 issue at time I am closing this one.

I opened this first before you assigned mt the ML code snippets. I was drafting the issue first.
