### ISSUE TITLE
[Feature Request]: Fun with Python GUI

### ISSUE THREAD

**Issue by OmmDevgoswami** [UTSAVS26/PySnippets#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I wish to contribute some fun projects that display the Graphical User-Interface performed by Python's module such as Turtle and tkinter.
This contribution is aimed to help user experience and learn the use of various GUI tools of Python.

My Contribution will have three programs includes:
1.Turtle Race Game : Using Python's built-in Turtle module
2.Pomodoro Timer : Using Python's tkinter module
3.Indian Map Game : Using Python's built-in Turtle and pandas module

![Screenshot 2024-10-08 191023](https://github.com/user-attachments/assets/402629cd-75c3-4b34-ab79-0fe38747a486)
![Screenshot 2024-10-08 191002](https://github.com/user-attachments/assets/072e0dbd-a167-45f7-a586-1a8c948c6df4)
![Screenshot 2024-10-08 190839](https://github.com/user-attachments/assets/d216abfc-5160-4db2-9f5f-e24e36522900)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Omm Devgoswami

### Participant Role

GSSOC extd and HacktoberFest 2024

**Comment by UTSAVS26** [comment]
@OmmDevgoswami sorry, but this repo is not for projects it's only for snippets that will help developers to use them directly without writing the code complete.
