### ISSUE TITLE
[Feature Request]: Emoji to Text Converter

### ISSUE THREAD

**Issue by decodingafterlife** [UTSAVS26/PySnippets#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A lot of times when working with texts, we come across emojis which can't be manipulated or used as a string data type. I propose the conversion of these emojis to text using libraries such as emote.

I wish to contribute to this under Hacktoberfest and GSSoC extd level 2.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Tanmay Shingavi

### Participant Role

GSSoC'24-extd

**Comment by M03anaswi** [comment]
@UTSAVS26 you can assign me this issue

**Comment by UTSAVS26** [comment]
> @UTSAVS26 you can assign me this issue
> 

You can raise another issue.
