### ISSUE TITLE
[Documentation Update]: Fixing The Structure And Writing Docs

### ISSUE THREAD

**Issue by SpreadSheets600** [UTSAVS26/PySnippets#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

@UTSAVS26 I am doing this since, people don't bother to follow the format and write docs.

### Suggested Change

I will fix up the format and write docs for the ones that are not present

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

SOHAM

### Participant Role

Hacktoberfest 
GSsoC-Extd

**Comment by UTSAVS26** [comment]
@SpreadSheets600 based on the output i will update the level to `level3`
