### ISSUE TITLE
 Flattening a Nested List 

### ISSUE THREAD

**Issue by ananyag309** [UTSAVS26/PySnippets#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This function flattens a nested list into a single list.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Ananya Gupta

### Participant Role

GSSOC extd. and Hacktoberfest

**Comment by KushagraSrivastava3010** [comment]
Please assign me this issue . I want to work on this matter. Please label it as gssoc ext level 1 and hactoberfest accepted.

**Comment by UTSAVS26** [comment]
> Please assign me this issue . I want to work on this matter. Please label it as gssoc ext level 1 and hactoberfest accepted.

Sorry you can raise a new issue.
