### ISSUE TITLE
[Feature Request]: Enhance the UI of the footer section

### ISSUE THREAD

**Issue by T-Fathima** [UTSAVS26/PySnippets#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current footer is too simple and i would to propose to add additional features such as quick links, contact etc to it and enhance the UI of the footer section.
I would like to work on it.
@UTSAVS26 Please assign it to me under gssoc-ext and hacktoberfest along with levels.
![image](https://github.com/user-attachments/assets/664e91ee-cb33-4291-bff3-1adc54e085fa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Tatheer Fathima

### Participant Role

Contributor in gssoc-ext and hacktoberfest

**Comment by UTSAVS26** [comment]
@T-Fathima you can only raise 1 issue at a time.
