### ISSUE TITLE
[Feature Request]: Add hover effect

### ISSUE THREAD

**Issue by T-Fathima** [UTSAVS26/PySnippets#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would to propose to add hover effect to these when clicked for better user interactivity
![image](https://github.com/user-attachments/assets/ef83e23d-21b1-46c0-bf69-9e74c2aa62dd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Tatheer Fathima

### Participant Role

Contributor in gssoc-ext and hacktoberfest

**Comment by UTSAVS26** [comment]
@T-Fathima you can only raise 1 issue at a time.

**Comment by UTSAVS26** [comment]
@T-Fathima you can only raise 1 issue at a time.
