### ISSUE TITLE
[Feature Request]: Add Footer section for website.

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [UTSAVS26/PySnippets#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The footer section is missing from your website.

![image](https://github.com/user-attachments/assets/c69ea101-4d9c-47a4-bd33-fbd7a42c8189)

I want to add a **Footer Section** and with necessary information:

- **Social Icons** 
- **Copyright**
- **Site info : Name and description**

Suggestions from my end: Twitter, Github, Instagram, LinkedIn. 
Please feel free to suggest any changes you want.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Rajdeep Chakraborty

### Participant Role

**Contributor**
Program - GSSoC 2024 Extended & Hactoberfest 2024.

**Comment by UTSAVS26** [comment]
@rajdeepchakraborty-rc the website has been created using `Google Sites` so it doesn't allow much customization.

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc the website has been created using `Google Sites` so it doesn't allow much customization.

Ok. Thanks a lot for the reply. I will try and look for other issues. Hope you have a great day ahead! 😀
