### ISSUE TITLE
[Feature Request]: AES Encryption script

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PySnippets#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There is no encryption algorithm in the snippets collection. In the ordinance of various encryption algorithms, AES or SHA-256 are the most basic & widely used encryption techniques that can encrypt the files.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

[Yash K. saini](https://github.com/yashksaini-coder)

### Participant Role

GSSOC-ext contributor

**Comment by yashksaini-coder** [comment]
@UTSAVS26 can you assign me this issue & add labels to it.

**Comment by UTSAVS26** [comment]
@yashksaini-coder based on the output i will change the level to 2
