### ISSUE TITLE
[Feature Request]: Adding Animated Footer To Website

### ISSUE THREAD

**Issue by GyanaPrakashSahoo7853** [UTSAVS26/PySnippets#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description
There is a lacks footer section in the website . An improved footer design can enhance usability and the overall look of the website.

###Describe the solution you'd like.

Changing the footer into better looking and responsive features

###Screenshots
![Screenshot 2024-10-13 205842](https://github.com/user-attachments/assets/a35e78b6-fd61-4823-8dd2-543af95fae39)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Gyana Prakash Sahoo

### Participant Role

GSSOC'24  Contributor

**Comment by githubashutoshsoni** [comment]
Hey, Can you please assign this to me?

**Comment by GyanaPrakashSahoo7853** [comment]
There is no index.html and css file of website provided by the PA

**Comment by UTSAVS26** [comment]
The website is created using Google Sites and it doesn't provide much customization.
