### ISSUE TITLE
[Feature Request]: Add all sorting Python Snippets

### ISSUE THREAD

**Issue by AnanteshG** [UTSAVS26/PySnippets#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

# To add the following Sorting Algorithms :-

- Bucket Sort
- Comb Sort
- Counting Sort
- Cycle Sort
- Gnome Sort
- Heap Sort
- Jump Sort
- Pigeon Hole Sort
- Radix Sort
- Selection Sort
- Shell Sort
- Stooge Sort
- Strand Sort
- Tree Sort

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Anantesh G

### Participant Role

GSSoC, Hacktoberfest

**Comment by AnanteshG** [comment]
@UTSAVS26 I have all the Sorting snippets ready. Should I add them in separate PRs or should I add them together? I see that you have given level 1 tag, that's the reason I asked.

**Comment by UTSAVS26** [comment]
> @UTSAVS26 I have all the Sorting snippets ready. Should I add them in separate PRs or should I add them together? I see that you have given level 1 tag, that's the reason I asked.

Add all of them in one PR as the thing why i given it level1 is that you are adding just code but if you fix any bug or adding new feature in the existing codebase that will be counted in higher level.

**Comment by omkarmakar** [comment]
I made a PR on this issue :)

I have added all the sorting algos needed
