### ISSUE TITLE
Tkinter snippets

### ISSUE THREAD

**Issue by lord-cyclone100** [UTSAVS26/PySnippets#2]
@UTSAVS26 
Hello bro....I would like to add some tkinter widget snippets such as lables, buttons, canvas etc....
I would like to contribute in your repo and so Pls assign me under hacktoberfest

**Comment by UTSAVS26** [comment]
@lord-cyclone100 
Hi there! Thanks for your interest in contributing to the repo. Could you please provide a more detailed explanation of why you'd like to add these Tkinter widget snippets? It would be helpful to know more specifics about what you plan to add and how it would improve or expand the current project. Looking forward to hearing more!

**Comment by lord-cyclone100** [comment]
@UTSAVS26 
The code snippets would be actually different types of gui elements like text boxes, buttons, radio and check boxes etc.....so that when users are trying to make any gui, they can use your repo instead of writing them again and again. I would also provide detailed explanation of what each method will perform....
I hope you understand 😀

**Comment by UTSAVS26** [comment]
okie @lord-cyclone100 , i am assigning you this but make sure to create proper snippets so that if any user want custom size text boxes and all they can easily be able to do it

**Comment by lord-cyclone100** [comment]
Just one question @UTSAVS26 
How would you like them?
In md files or py files?

**Comment by UTSAVS26** [comment]
> Just one question @UTSAVS26 How would you like them? In md files or py files?
you are creating code snippets so they need to be in py files and if explanation and working things you are write md files for them
