### ISSUE TITLE
[Documentation Update]: Add Readme Template For Each Folder And Code Organization

### ISSUE THREAD

**Issue by SpreadSheets600** [UTSAVS26/PySnippets#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

@UTSAVS26 As Discussed With You This Issue Is For The Code Organization

### Suggested Change

1. Adding Documentation Template For Each Section
2. Fixing Folder Names 
3. Adding Folders In Tests
4. Fixing The Folder Rename Issue In Test Cases

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by patiltrupti6105** [comment]
I am keen to help on this issue and willing to collaborate if possible.

**Comment by UTSAVS26** [comment]
@SpreadSheets600 your decision, you wanna work with @patiltrupti6105 on this issue?

**Comment by SpreadSheets600** [comment]
> @SpreadSheets600 your decision, you wanna work with @patiltrupti6105 on this issue? 

Sure I will be glad to work with @patiltrupti6105 
Please dm on discord : SpreadSheets600

**Comment by patiltrupti6105** [comment]
Thank you @SpreadSheets600

**Comment by UTSAVS26** [comment]
I am assigning this issue to @patiltrupti6105 too.
