### ISSUE TITLE
[Feature Request]: Adding Searching python-snippets

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PySnippets#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hi @UTSAVS26 in this collection there are no proper searching algorithms that can be used by the developers. I would like to add searching algos starting from the basic and then altogether go to intermediate & advanced. 

![image](https://github.com/user-attachments/assets/f9d435e8-9d98-48bd-85f3-c220cf3317a3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

[Yash K. Saini](https://github.com/yashksaini-coder)

### Participant Role

GSSOC

**Comment by yashksaini-coder** [comment]
Hi @UTSAVS26 can you assign me this issue with proper labels, also check the #198 PR, I have completed the previous issue I was assigned and raised a PR successfully.

**Comment by yashksaini-coder** [comment]
Also there is another updation I would like you to see, if it is a better improvement to be included in the README and in this repo website

**Comment by yashksaini-coder** [comment]
Can you assign me this issue @UTSAVS26

**Comment by yashksaini-coder** [comment]
@UTSAVS26 can you assign me this issue

**Comment by yashksaini-coder** [comment]
I want to add more & better searching algorithms in the searching dir, all with their proper time complexity analysis, and also better readability @UTSAVS26

**Comment by UTSAVS26** [comment]
@yashksaini-coder correct the already existing algos, as i have given it level3.

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder correct the already existing algos, as i have given it level3. 

Okh understood 
Also can you review the PR again I messaged you on discord server
