### ISSUE TITLE
[Feature Request]: Add heapsort in sorting algorithms

### ISSUE THREAD

**Issue by Chinmayeep58** [UTSAVS26/PySnippets#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to contribute to this project by adding the heap sort algorithm. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Chinmayee P

### Participant Role

GSSoC

**Comment by jiyabansal123** [comment]
@Chinmayeep58 Chinmayeep58 can you assign this to me
