### ISSUE TITLE
[Feature Request]: New 'random' module and 'password generator' code

### ISSUE THREAD

**Issue by trinetra110** [UTSAVS26/PySnippets#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a `random` module snippet and add the `password generator` code under it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Ayan Mondal

### Participant Role

GSSOC-Extd, Hacktoberfest

**Comment by jiyabansal123** [comment]
please add hacktober fest label and assign me this issue
