### ISSUE TITLE
[Feature Request]: Add python code for movies recommendation using web scrapping

### ISSUE THREAD

**Issue by Amanjayswal500** [UTSAVS26/PySnippets#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

by using web scrapping we recommend movies and also provide link of the movies 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Aman Jayswal

### Participant Role

gssoc extd

hacktobefest

**Comment by NancyCoderina** [comment]
I would like to work on this project . Please assign it to me.
