### ISSUE TITLE
[Feature Request]: Replace numbers with corresponding word and vice versa

### ISSUE THREAD

**Issue by Panda8Bamboo** [UTSAVS26/PySnippets#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Replace numbers with corresponding word in a string and vice versa in string_manipulation

3 functions:

1. One to replace just numbers to corresponding word
    "6 years ago there were five." becomes "Six years ago there were five."

2. One to do the inverse
    "There are eight men but now 5." becomes "There are 8 men but now 5."

3. And one that swaps both
    "6 years ago there were eight men" becomes "Six years ago there were 8 men"

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Amber

### Participant Role

GSOC

**Comment by SKG24** [comment]
Could you let me know if there will be single digit numbers or multiple digits?

**Comment by SKG24** [comment]
I would like to work on this please assign this to me. I have implemented the code for single digit conversions

Name : Sanat Kumar Gupta
Participation : GSSOC'24 ext, hackoctober
