### ISSUE TITLE
Feature: Proposal to Add Snippets Using Popular Python Libraries (pandas, NumPy, requests, matplotlib)!

### ISSUE THREAD

**Issue by Ishratnoori** [UTSAVS26/PySnippets#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@UTSAVS26  I would like to contribute by adding Python snippets using popular libraries such as pandas, NumPy, requests, and matplotlib. Could you please assign me this task? Thanks!
I’m looking forward to contributing!

Best regards,  
Ishrat noori :) 
(Please assign me under gssoc-ext, contributor and hacktoberfest) :))

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

MOHAMMAD ISHRAT NOORI

### Participant Role

GSSOC

**Comment by jiyabansal123** [comment]
@UTSAVS26 please assign this to me, i would also like to contribute to this

**Comment by Ishratnoori** [comment]
@jiyabansal123 Lets solve this together?

**Comment by Ishratnoori** [comment]
Hello @UTSAVS26 !

I've already done with this task few weeks ago .kindly close this issue :)

**Comment by UTSAVS26** [comment]
> Hello @UTSAVS26 !
> 
> I've already done with this task few weeks ago .kindly close this issue :)

Send me PR link.

**Comment by Ishratnoori** [comment]
Hello @UTSAVS26 _!_

Here is the PR link..!  **https://github.com/UTSAVS26/PySnippets/pull/266**
