### ISSUE TITLE
Adding effects on Landing page

### ISSUE THREAD

**Issue by 1754riya** [UTSAVS26/PySnippets#257]
Adding effects on the Landing page.
![Screenshot (369)](https://github.com/user-attachments/assets/23274854-0cd6-4394-8a72-6de6e52c7dcc)

Please, assign me this under gssoc'24 and hacktoberfest.

**Comment by UTSAVS26** [comment]
The website has been created using Google Sites so there is no code for it. If you want to create one you can raise new issue for that.
