### ISSUE TITLE
 Improve `send_email.py` for Enhanced Security, Consistency, and Flexibility

### ISSUE THREAD

**Issue by smog-root** [UTSAVS26/PySnippets#300]
The current implementation of send_email.py works well for sending basic emails, but there are a few areas for improvement. These changes will enhance security, consistency, and flexibility in the email-sending functionality.
Suggested Improvements

_**I'm expecting gssoc-ext with a level and hacktoberfest-accepted labels!!**_ @UTSAVS26 

**1. Fix Typo in Docstring:**
        
- Update recepient_mail to recepient_email in the docstring under Args to match the function parameter.

**2. Improve Security by Avoiding Hardcoded Credentials:**

- Replace hardcoded credentials with environment variables. This will prevent sensitive information from being exposed in the code.
- Update the if __name__ == "__main__": block to load credentials from environment variables instead.

**3. Allow HTML Formatting in Email Body:**

- Add an optional parameter to specify the email content type (e.g., "plain" or "html").
- Modify the code to support HTML content in the email body if specified.

**4. Add Network Error Handling:**

- Enhance error handling by catching network-related errors, such as connection timeouts, to provide better feedback when email sending fails.

**5. Add Type Hints:**

- Add type hints to the function parameters and return type for better readability and to leverage type checking.

**Comment by UTSAVS26** [comment]
@smog-root Hacktoberfest is end now so no labels related to Hacktoberfest is gonna add from now on.
