### ISSUE TITLE
Code Review and Enhancements for Cipher Implementations

### ISSUE THREAD

**Issue by smog-root** [UTSAVS26/PySnippets#308]
I would like to request a code review and suggestions for enhancements on the following cipher implementations in you'r project:

**_I'm expecting a gssoc-ext with level label._** @UTSAVS26 

**1. Affine Cipher (affine_cipher.py):**
        
- Currently implements encryption and decryption using the Affine cipher.
        
- **Potential Improvements:**
- Validate that the 'a' parameter is coprime with 26.
- Consider supporting lowercase characters without losing case sensitivity.

**2. Caesar Cipher (caesar_cipher.py):**
        
- Implements a Caesar cipher with encryption, decryption, and brute-force decryption functionality.
        
**Potential Improvements:**
 - Add handling for non-string inputs in the encrypt and decrypt methods.
 - Consider modularizing the class structure to facilitate state management.

**3. Playfair Cipher (playfair_cipher.py):**
        
- Implements Playfair cipher encryption and decryption with key table generation and text preprocessing.
        
- **Potential Improvements:**
- Add error handling for non-alphabetic characters during text preprocessing.
- Consider encapsulating the functionality within a class for better organization and state management.

**Comment by yashksaini-coder** [comment]
thx for pointing out the problems in my code @smog-root buddy, appreciate the efforts

**Comment by UTSAVS26** [comment]
@smog-root work on it and i will directly check the PR and label on it.

**Comment by smog-root** [comment]
@UTSAVS26 assign me!
