### ISSUE TITLE
Build Script: Write a script that build & deploy the package.

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PySnippets#313]
Main aim is to create a bash script to automate the process of building & deploying a python package with one script without running any commands, 

Let's user use their own setup.py or prompt the user to take input and then create a setup.py from scratch, also (maybe possible to add a .env file to access values of user's choice).

@UTSAVS26 can you review this issue and assign it to me. at least `level 3`

**Comment by NK-Works** [comment]
@UTSAVS26 i can work on it 
please assign it to me
