### ISSUE TITLE
Improve and Fix Issues in image_Processing

### ISSUE THREAD

**Issue by smog-root** [UTSAVS26/PySnippets#323]
**Tasks:**

- Review all model files for potential performance optimizations.
- Refactor code to improve readability and remove redundancies.
- Fix any existing bugs in the model logic or structure.
- Add comments and documentation for better understanding.
- Write unit tests to verify model accuracy and reliability.

**Additional Context:** Ensure all changes align with the repository’s coding standards and best practices. This update is intended to make the models more robust and efficient for current and future use.

**_You can add the level label after PR submission!_**  @UTSAVS26

**Comment by UTSAVS26** [comment]
Raise PR I will add labels directly to it.
