### ISSUE TITLE
[Feature Request]: Build Script: Write a script to install the required dependencies

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PySnippets#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Creating a script(install.sh) to install the prerequisites required for the build & publish package

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

[Yash K. Saini](https://github.com/yashksaini-coder)

### Participant Role

GSSoC-Ext

**Comment by yashksaini-coder** [comment]
@UTSAVS26 kindly assign me this issue

**Comment by UTSAVS26** [comment]
@yashksaini-coder you can raise PRs after raising issues I will add labels and assign you on PR directly. And complete all those raised issues that you raised.

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder you can raise PRs after raising issues I will add labels and assign you on PR directly. And complete all those raised issues that you raised.

Yes I will,
