### ISSUE TITLE
[Feature Request]: Searching and Sorting Algorithms in Python with Test Cases

### ISSUE THREAD

**Issue by simrantyagi01** [UTSAVS26/PySnippets#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This Python script will provide several commonly used searching and sorting algorithms. The searching algorithms include linear search, binary search, jump search, and exponential search, while the sorting algorithms will feature bubble sort, selection sort, insertion sort, merge sort, quick sort, heap sort, counting sort, and radix sort. Each algorithm will be implemented to handle common edge cases, such as empty arrays or arrays with duplicate elements.A separate test file (test_searching_sorting.py) will be included to validate the correctness of each algorithm using the unittest framework. The tests will cover various scenarios and edge cases to ensure the functions are efficient and reliable.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by pavitraag** [comment]
I would like to work on this . Please assign me under gssoc and hacktoberfest
