### ISSUE TITLE
[Feature Request]: Adding a euler function

### ISSUE THREAD

**Issue by Kritika75** [UTSAVS26/PySnippets#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey, how about we enhance the mathematics module by adding an Euler function along with a visualization feature, such as a bar chart?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Kritika Singh

### Participant Role

Open source contributor, i am not participating in any ongoing program, but i was in GSSOC'24 extd.

@UTSAVS26 can i work on this issue?

**Comment by UTSAVS26** [comment]
okie go ahead @Kritika75
