### ISSUE TITLE
[Feature Request]: Add list manipulation methods

### ISSUE THREAD

**Issue by mehul-m-prajapati** [UTSAVS26/PySnippets#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The List Manipulation Module provides essential functions for working with lists, enabling efficient data handling and analysis. Each function is designed to facilitate common tasks related to list operations.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by UTSAVS26** [comment]
Sorry @mehul-m-prajapati I am closing this issue too as no one assigned you the issue and you raised a PR.

**Comment by mehul-m-prajapati** [comment]
> Sorry @mehul-m-prajapati I am closing this issue too as no one assigned you the issue and you raised a PR.

I am working from different time zone. That is why I was working on PR.

From now onwards, I will wait for your assignment.

Thanks,
Mehul
