### ISSUE TITLE
[Feature Request]: Adding Utilitiy functions

### ISSUE THREAD

**Issue by htanmo** [UTSAVS26/PySnippets#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding a new package named "utilities" for commonly used utility functions.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ShudarsanRegmi** [comment]
Can I try it too? Can an issue be assigned to multiple users? Me too working for gssoc-ext.

**Comment by UTSAVS26** [comment]
> Can I try it too? Can an issue be assigned to multiple users? Me too working for gssoc-ext. 

You can raise another issue as this one is already assigned and the contributor is already working on it.
