### ISSUE TITLE
Adding more complex number functions.

### ISSUE THREAD

**Issue by htanmo** [UTSAVS26/PySnippets#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Supersedes issue #17
@UTSAVS26

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ShudarsanRegmi** [comment]
I'm doing gssoc-ext. Can you assign me suitable labels.

**Comment by htanmo** [comment]
@UTSAVS26 I have created the new issue as asked and also referenced it in my previous pull request please verify.

**Comment by htanmo** [comment]
@UTSAVS26 please review it
