### ISSUE TITLE
[Feature Request]: Make the information into cards

### ISSUE THREAD

**Issue by snehaapratap** [UTSAVS26/PySnippets#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Making the information into cards will make the website more dynamic and readable to the users.
![image](https://github.com/user-attachments/assets/44ba757e-77ae-41e7-8565-1c2cedc3e913)

if these are implemented as cards , they will be a very attractive website feature.
kindly assign me this task.
Thank you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by snehaapratap** [comment]
@UTSAVS26 but i shall definitely try changing them.
kindly assign me this task and i shall start working on it.

**Comment by UTSAVS26** [comment]
@snehaapratap you are going to create new website for it or just the cards?

**Comment by snehaapratap** [comment]
ill create a new website, but if you want i can maybe create only for the cards as well.
