### ISSUE TITLE
[Feature Request]: Adding python basic algorithms

### ISSUE THREAD

**Issue by Prem-Kumar-Dev** [UTSAVS26/PySnippets#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding basic algorithms in python like basic sorting and searching  algorithms

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by wizaye** [comment]
hey @Prem-Kumar-Dev  i would like to work on this could you give me more details and assign this to me?

**Comment by Prem-Kumar-Dev** [comment]
@wizaye already working on it.

**Comment by Prem-Kumar-Dev** [comment]
hey, @wizaye  its open source so don't think much and contribute whatever you can.

**Comment by Prem-Kumar-Dev** [comment]
@UTSAVS26 uploaded basic sorting and searching algorithms, please review and close
