### ISSUE TITLE
[Documentation Update]: Imporve README documentation

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PySnippets#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Current README docs is not much informative and engaging to the other contributors

### Suggested Change

Add badges & sections with different indexes make it easy to navigate in the README doc

@UTSAVS26 I want to work on this issue can U assign this issue to me as Gsssoc'24 contributor

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ashmittt08** [comment]
@UTSAVS26 I want to work on this issue  as well ,can you please assign this issue to me as Gsssoc'24 contributor

**Comment by UTSAVS26** [comment]
> @UTSAVS26 I want to work on this issue  as well ,can you please assign this issue to me as Gsssoc'24 contributor

This issue is already been assigned

**Comment by ashmittt08** [comment]
so will you assign this to me and consider the changes??

**Comment by UTSAVS26** [comment]
> so will you assign this to me and consider the changes??

Can't be possible as it is already assigned to @yashksaini-coder

**Comment by yashksaini-coder** [comment]
@ashmittt08 It is first come first serve basis, if you are a GSSOC participant, please follow the GSSOC rules.

**Comment by AnujSaha0111** [comment]
I want to contribute on the issue. Can you please assign it to me?

**Comment by UTSAVS26** [comment]
> I want to contribute on the issue. Can you please assign it to me?

You need to raise another issue as it is already been assigned.
