### ISSUE TITLE
[Feature Request]: Addition of Web Develeopment Projects | DocXtract and DevDetective

### ISSUE THREAD

**Issue by Shariq2003** [UTSAVS26/PySnippets#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of Web Develeopment Projects | DocXtract and DevDetective

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by UTSAVS26** [comment]
@Shariq2003 this is not a right project in which you can web development project.
