### ISSUE TITLE
[Feature Request]: Add data plotting snippets

### ISSUE THREAD

**Issue by PavanTeja2005** [UTSAVS26/PySnippets#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This snippets should include data visualization snippets. I want to add them.

I'm a gssoc extended contributor. Please assign me with it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by UTSAVS26** [comment]
@PavanTeja2005 you can raise 1 issue at a time.
