### ISSUE TITLE
[Feature Request]: Machine Learning models code-snippets

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PySnippets#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add different machine learning models code that are widely used in the data science **classification** and **prediction** purposes. Furthermore share a brief working algorithms using raw python code.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by yashksaini-coder** [comment]
@UTSAVS26 can you assign me this issue & add labels to it. `gssoc-ext`, `hacktoberfest`, `hacktoberfest-accepted` etc

**Comment by UTSAVS26** [comment]
@yashksaini-coder raise 1 issue at a time based on the rules on discussion.
