### ISSUE TITLE
[Feature Request]: Sorting algorithms

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PySnippets#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I have gone through the codebase & found that there are no sorting algorithms in the project. I can work to provide different sorting algorithms with their documentation too so that it provides a clear informative material to the other DEVS.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by yashksaini-coder** [comment]
@UTSAVS26 can you assign this issue to me & Add labels to it `gssoc-ext`, `hacktoberfest`, `hacktoberfest-accepted`

**Comment by UTSAVS26** [comment]
@yashksaini-coder raise 1 issue at a time based on the rules on discussion.
