### ISSUE TITLE
[Documentation Update]: Addition of File organizer snippet

### ISSUE THREAD

**Issue by priyanka350** [UTSAVS26/PySnippets#9]
### Is there an existing issue for this? - no

- [X] I have searched the existing issues

### Issue Description

I want to propose my idea of adding a file organizer snippet which organize files in a folder based on their file type (e.g., documents, images, videos, etc.).

### Suggested Change

Addition of file organizer pysnippet under pysnippets.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by UTSAVS26** [comment]
@priyanka350 you are GSSOC Contributor right?

**Comment by priyanka350** [comment]
@UTSAVS26 yes I am gssoc extd contributor
