### ISSUE TITLE
[Bug]: Quantile code-snippet lacks upper & lower quartiles

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PySnippets#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The below code provides only the 50% range i.e. the middle of the dataset. It fails to divide the dataset in 3 groups of upper, middle & lower. I would like to fix this code & complete it to provide all the working of the **Quantile statistical measure**

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9f7859f0-d263-4483-a020-a0ef86b03932)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by yashksaini-coder** [comment]
@UTSAVS26 can you assign this issue to me & add labels to it `gssoc-ext`, `hacktoberfest`, `hacktoberfest-accepted`, `Level 3`

**Comment by UTSAVS26** [comment]
@yashksaini-coder raise 1 issue at a time based on the rules on discussion.
